version: "3"

services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    tty: true
    environment:
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql:/var/lib/mysql