version: "3"

services:
  db:
    image: postgres:9.4
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - "5432:5432"